apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: bookinfo
  labels:
    app.kubernetes.io/name: ratings
    app.kubernetes.io/part-of: bookinfo
spec:
  type: ClusterIP
  selector:
    app: ratings
  ports:
    - name: http
      port: 9080
      targetPort: 9080
