apiVersion: v1
kind: Service
metadata:
  name: mesh-webhook
  namespace: mesh-system
  labels:
    app.kubernetes.io/name: mesh-webhook
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: service-mesh
spec:
  selector:
    app.kubernetes.io/name: mesh-webhook
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
