#!/usr/bin/env python3
"""
Рекурсивно обходит директорию и объединяет содержимое всех файлов в один,
добавляя перед каждым блоком относительный путь к файлу.
"""

import os
import sys
import argparse
from pathlib import Path

# Расширения текстовых файлов (можно дополнить)
TEXT_EXTENSIONS = {'.md', '.yaml', '.yml'}

def collect_files_content(root_dir, output_file, skip_binary=True, exclude_dirs=None):
    """
    root_dir: начальная директория
    output_file: путь к выходному файлу
    skip_binary: пропускать бинарные файлы
    exclude_dirs: список имён директорий для пропуска (например, ['.git', '__pycache__'])
    """
    if exclude_dirs is None:
        exclude_dirs = ['.git', '__pycache__', 'node_modules', '.idea', 'venv', 'env']
    
    root_path = Path(root_dir).resolve()
    output_path = Path(output_file)
    
    with open(output_path, 'w', encoding='utf-8') as out_f:
        out_f.write(f"Generated by scrapper.py from directory: {root_path}\n\n")
        for current_dir, dirs, files in os.walk(root_dir, topdown=True):
            # Исключаем ненужные директории из обхода
            dirs[:] = [d for d in dirs if d not in exclude_dirs and not d.startswith('.')]
            
            for file_name in files:
                file_path = Path(current_dir) / file_name
                
                # Пропускаем символические ссылки
                if file_path.is_symlink():
                    continue
                
                # Пропускаем бинарные файлы, если требуется
                if file_path.suffix.lower() not in TEXT_EXTENSIONS:
                    continue

                # Относительный путь от корневой директории
                relative_path = Path(file_path).resolve().relative_to(root_path)
                
                # Записываем заголовок
                out_f.write(f"\n--- {relative_path} ---\n\n")
                
                # Читаем и записываем содержимое
                try:
                    with open(file_path, 'r', encoding='utf-8') as in_f:
                        content = in_f.read()
                    out_f.write(content)
                    if not content.endswith('\n'):
                        out_f.write('\n')  # добавляем перенос для разделения
                except UnicodeDecodeError:
                    # Если файл определился как текстовый, но не UTF-8, пробуем другие кодировки
                    try:
                        with open(file_path, 'r', encoding='latin-1') as in_f:
                            out_f.write(in_f.read())
                        out_f.write('\n')
                    except Exception as e:
                        out_f.write(f"[Ошибка чтения файла: {e}]\n")
                except Exception as e:
                    out_f.write(f"[Ошибка чтения файла: {e}]\n")
    
    print(f"Содержимое сохранено в {output_path.resolve()}")

def main():
    parser = argparse.ArgumentParser(
        description="Объединить содержимое всех файлов из директории в один файл с указанием путей."
    )
    parser.add_argument('directory', nargs='?', default='.',
                        help='Корневая директория (по умолчанию текущая)')
    parser.add_argument('-o', '--output', default='combined_output.txt',
                        help='Выходной файл (по умолчанию combined_output.txt)')
    parser.add_argument('--include-binary', action='store_true',
                        help='Включать бинарные файлы (не рекомендуется)')
    parser.add_argument('--exclude', nargs='+', default=None,
                        help='Дополнительные имена папок для исключения')
    args = parser.parse_args()
    
    exclude_dirs = ['.git', '__pycache__', 'node_modules', '.idea', 'venv', 'env']
    if args.exclude:
        exclude_dirs.extend(args.exclude)
    
    collect_files_content(
        root_dir=args.directory,
        output_file=args.output,
        skip_binary=not args.include_binary,
        exclude_dirs=exclude_dirs
    )

if __name__ == '__main__':
    main()