apiVersion: v1
kind: ServiceAccount
metadata:
  name: mesh-webhook
  namespace: mesh-system
  labels:
    app.kubernetes.io/name: mesh-webhook
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: service-mesh
